name: Question
description: Ask a question about thing
labels: ["question"]
body:
  - type: markdown
    attributes:
      value: |
        **Ask a question about thing**

  - type: textarea
    attributes:
      label: Question
      description: Describe your question in detail.
    validations:
      required: true

  - type: input
    attributes:
      label: Platform
      description: What operating system and architecture are you using? (see `uname -orsm`)
      placeholder: e.g., macOS 14 arm64, Windows 11 x86_64, Ubuntu 20.04 amd64
    validations:
      required: false

  - type: input
    attributes:
      label: Version
      description: What version of thing are you using? (see `thing self version`)
      placeholder: e.g., thing 0.1.0
    validations:
      required: false
